### ISSUE TITLE
Missing resources

### ISSUE THREAD

**Issue by alerque** [openscriptures/Biblelator#2]
At least some resources seem to be missing from the git repo:

```
Biblelator: Platform is linux
Biblelator: OS name is posix
Biblelator: OS uname is posix.uname_result(sysname='Linux', nodename='jaguar', release='4.4.5-1-ARCH', version='#1 SMP PREEMPT Thu Mar 10 07:38:19 CET 2016', machine='x86_64')
Biblelator: Running main…
Biblelator v0.31 last modified 2016-03-23
Windowing system is 'x11'
Traceback (most recent call last):
  File "./Biblelator.py", line 2430, in <module>
    main( homeFolderPath, loggingFolderPath )
  File "./Biblelator.py", line 2390, in main
    iconImage = tk.PhotoImage( file='Biblelator.gif' )
  File "/usr/lib/python3.5/tkinter/__init__.py", line 3393, in __init__
    Image.__init__(self, 'photo', name, cnf, master, **kw)
  File "/usr/lib/python3.5/tkinter/__init__.py", line 3349, in __init__
    self.tk.call(('image', 'create', imgtype, name,) + options)
_tkinter.TclError: couldn't open "Biblelator.gif": no such file or directory
```

Wherever this gif is supposed to come from it doesn't seem to be in the repo or any of the other things the setup instructions had me clone.

**Comment by RobH123** [comment]
```
Missing file now committed to master. Thanks Caleb.

On 24/03/16 23:33, Caleb Maclennan
  wrote:


  At least some resources seem to be missing from the git repo:
  Biblelator: Platform is linux
```

Biblelator: OS name is posix
Biblelator: OS uname is posix.uname_result(sysname='Linux', nodename='jaguar', release='4.4.5-1-ARCH', version='#1 SMP PREEMPT Thu Mar 10 07:38:19 CET 2016', machine='x86_64')
Biblelator: Running main…
Biblelator v0.31 last modified 2016-03-23
Windowing system is 'x11'
Traceback (most recent call last):
  File "./Biblelator.py", line 2430, in <module>
    main( homeFolderPath, loggingFolderPath )
  File "./Biblelator.py", line 2390, in main
    iconImage = tk.PhotoImage( file='Biblelator.gif' )
  File "/usr/lib/python3.5/tkinter/**init**.py", line 3393, in **init**
    Image.**init**(self, 'photo', name, cnf, master, **kw)
  File "/usr/lib/python3.5/tkinter/**init**.py", line 3349, in **init**
    self.tk.call(('image', 'create', imgtype, name,) + options)
_tkinter.TclError: couldn't open "Biblelator.gif": no such file or directory

```
  Wherever this gif is supposed to come from it doesn't seem to
    be in the repo or any of the other things the setup instructions
    had me clone.
  —
    You are receiving this because you are subscribed to this
    thread.
    Reply to this email directly or view
      it on GitHub
```

**Comment by alerque** [comment]
Committed maybe, but perhaps you forgot to push?

**Comment by RobH123** [comment]
I'm aware on holiday for a day or two. Pretty sure I pushed the 
temporary logo file, but on reflection, it may have gone to only one of 
the branches??? Check master and development.

Sorry,
Robert.

**Comment by alerque** [comment]
Aaa, it does look like it ended up in the development branch. I'll check it out there when I get a chance.
